name: emissions
channels:
  - nvidia/label/cuda-11.5.0
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - cuda-nvcc=11.5
  - cuda-libraries-dev=11.5
  - cxx-compiler
  - gxx=10
  - make
  - libopenblas
  - openblas
  - clblast
  - libcblas
  - ocl-icd-system
  - git-lfs
