name: axolotl
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cuda=11.8
  - cuda-nvcc=11.8
  - cuda-libraries-dev=11.8
  - cxx-compiler
  - gxx=10
  - pip
  - make
  - packaging
  - pyinstaller
  - pytorch=2.0.1
  - pytorch-cuda=11.8
